language: php

php:
  - 7.2

sudo: false

env:
  - APP_DEBUG=false

install:
  - cp .env.travis .env
  - composer install --prefer-dist --quiet
  - php artisan key:generate

script: vendor/bin/phpunit -c phpunit.xml --coverage-text
